In [1]:
import pandas as pd

In [4]:
pd0 = pd.read_csv("MatchedResult_0.txt",header=None)

In [5]:
def remove_punc(str_item):
    str_item = str_item.replace(')','')
    str_item = str_item.replace('(','')
    return str_item

In [6]:
pd0 = pd.read_csv("MatchedResult_0.txt",header=None)

pd0['short'] = pd0.iloc[:, 0].apply(remove_punc)
pd0['long'] = pd0.iloc[:, 1].apply(remove_punc)

pd0 = pd0.iloc[:, 2:4]

In [7]:
pd1 = pd.read_csv("MatchedResult_1.txt",header=None)

pd1['short'] = pd1.iloc[:, 0].apply(remove_punc)
pd1['long'] = pd1.iloc[:, 1].apply(remove_punc)

pd1 = pd1.iloc[:, 2:4]

In [8]:
pd2 = pd.read_csv("MatchedResult.txt",header=None)

pd2['short'] = pd2.iloc[:, 0].apply(remove_punc)
pd2['long'] = pd2.iloc[:, 1].apply(remove_punc)

pd2 = pd2.iloc[:, 2:4]

In [9]:
frames = [pd0, pd1, pd2]

pd_input1 = pd.concat(frames)

In [10]:
# rst_temp = pd_input1.groupby('short').count()
rst_temp = pd_input1.groupby('short')['long'].apply(list)
# rst_temp[rst_temp.index == '10156']
rst_temp

short
1003667    [ 1011956]
1132169    [ 1132169]
1136543    [ 1136543]
1141309    [ 1141309]
1503380    [ 1503380]
1512605    [ 1512605]
1518129    [ 1518129]
1521170    [ 1521170]
1521171    [ 1521171]
1521172    [ 1521172]
1521174    [ 1521174]
1521175    [ 1521175]
1521176    [ 1521176]
1521178    [ 1521178]
1521180    [ 1521180]
1521181    [ 1521181]
1521182    [ 1521182]
1522481    [ 1522481]
1689327    [ 1689327]
1697792    [ 1697792]
1703766    [ 1703766]
1709322    [ 1709322]
1714043    [ 1714043]
2933294    [ 4222428]
2937322    [ 2937322]
2937323    [ 2937323]
2937324    [ 2937324]
2937326    [ 2937326]
2937327    [ 2937327]
2937328    [ 2937328]
              ...
6421807    [ 6421807]
6421824    [ 6347071]
6422115    [ 6422115]
6422353    [ 6373326]
6423433    [ 6423433]
6425814    [ 6424941]
6428559    [ 6417258]
6428561    [ 6417360]
6428876    [ 6428876]
6432389    [ 6428464]
6432400    [ 6428464]
6432410    [ 6428464]
6432421    [ 6428464]
6432424    [ 6428464]
6432430    [ 6428464]
6432431    [ 6428464]
6434738    [ 6434738]
6435528    [ 6435528]
6435534    [ 6435534]
6435536    [ 6435536]
6435542    [ 6435542]
6436214    [ 6417360]
6436218    [ 6420705]
6436227    [ 6417360]
678330      [ 678330]
678332      [ 678332]
678333      [ 678333]
678334      [ 678334]
678335      [ 678335]
678336      [ 678336]
Name: long, Length: 11772, dtype: object

In [11]:
pd_rst = pd_input1.groupby('short').head(1)
# pd_rst[pd_rst.short == '10156']
pd_rst

        short      long
0     1521175   1521175
1     1714043   1714043
2     1132169   1132169
3     1136543   1136543
4     1512605   1512605
5     1521181   1521181
6     1697792   1697792
7     1689327   1689327
8     1003667   1011956
9     1503380   1503380
10    1521178   1521178
11    1521180   1521180
12    1518129   1518129
13    1521170   1521170
14    1521171   1521171
15    1521174   1521174
16    1521182   1521182
17    1141309   1141309
18    1703766   1703766
19    1521172   1521172
20    1521176   1521176
21    1522481   1522481
22    1709322   1709322
23    2933294   4222428
24    2938772   2938834
25    2938778   2938681
26    2938787   2938681
27    2938788   2938834
28    2938790   2938834
29    2938793   2938462
...       ...       ...
2376  6358600   6347982
2377  6361380   6361380
2378  6362035   6362035
2379  6366264   6366264
2380  6368017   6368017
2381  6371474   6371474
2382  6371673   6371673
2383  6389271   6389271
2384  6389931   6432745
2385  6393780   6393780
2386  6400071   6373326
2387  6400733   6400733
2388  6404267   6404267
2389  6404278   6404278
2390  6404287   6404287
2391  6404291   6404291
2392  6404362   6404362
2393  6405906   6456061
2394  6408004   6353184
2395  6408011   6353121
2396  6408494   6408494
2397  6411397   6411397
2398  6415314   6415314
2399  6419516   6419512
2400  6428561   6417360
2401  6432389   6428464
2402  6432421   6428464
2403  6432430   6428464
2404  6432431   6428464
2405  6436218   6420705

[11772 rows x 2 columns]

In [16]:
pd_rst.count()

# 62415

short    11772
long     11772
dtype: int64

In [15]:
pd_rst.to_csv('matched_rst.csv',header=True)